# Generated by Django 4.2 on 2023-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='input_time',
            field=models.DateField(auto_now=True, verbose_name='입고'),
        ),
        migrations.AddField(
            model_name='product',
            name='out_time',
            field=models.DateField(auto_now=True, verbose_name='출고'),
        ),
    ]
