# Generated by Django 4.2 on 2023-04-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_input_time_remove_product_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='input_time',
            field=models.DateField(auto_now=True, verbose_name='입고'),
        ),
    ]
